version: '3.4'

services:
  ## USERS SERVICE
  users:
    container_name: users
    build:
      context: ./backend/users
      dockerfile: Dockerfile-prod
  expose:
    - '5000'
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.ProdConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db
  ## PG USERS
  users-db:
    container_name: users-db
    build:
      context: ./backend/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  ## REVERSE PROXY
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
  ## FRONT    
  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    args:
      - NODE_ENV=production
    ports:
      - '3007:80'
    depends_on:
      - users

