version: '3.4'

services:
  ## USERS SERVICE
  users:
    container_name: users
    build:
      context: ./backend/users
      dockerfile: Dockerfile-dev
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db
  ## PG USERS
  users-db:
    container_name: users-db
    build:
      context: ./backend/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  ## REVERSE PROXY
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 81:80
    depends_on:
      - users
      - client
  ## FRONT
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - users
